### ISSUE TITLE
Rediseñar la estructura del Flone para montar la cámara abajo - Redesign the frame for mounting the camera below the Flone

### ISSUE THREAD

**Issue by gpereyrairujo** [vuelaendron/vuela#15]
El Flone está diseñado para utilizar un teléfono montado arriba como cámara. Para utilizar otro tipo de cámaras habría que montarlas debajo (donde ahora va la batería). Para ello habría que rediseñar la estructura del Flone (archivo original aquí: https://github.com/aeracoop/flone-frame).
- - -
The Flone is designed to use a phone mounted above as a camera. To use other types of cameras, they should be mounted below (where the battery is now). To do so, the frame of the Flone should be redesigned (original file here: https://github.com/aeracoop/flone-frame).

**Comment by cala2** [comment]
Tambien se puede evaluar montarla al frente y balancear con la batt, correria menos riesgo de morir aplastada en un crash.

**Comment by cala2** [comment]
Si, esta muy buena, aun en el caso que no se le quiera poner el gimbal porque solo se tomaran fotos hacia abajo y para tener mas autonomia, tb la pondria delante.
Sacando un soporte rigido hacia adelante y colocando el gimbal con las gomitas colgado alli no les resolveria el problema quizas?

**Comment by gpereyrairujo** [comment]
En varios de los talleres surgió la idea de poner la cámara/teléfono abajo, ya que le vemos varias ventajas:
- es más fácil usar distintos tipos de cámaras (no sólo teléfonos)
- es más fácil aislar las vibraciones de los motores (como vimos acá: https://github.com/vuelaendron/vuela/issues/6#issuecomment-399790722)
- es la mejor posición para obtener fotos hacia abajo (no videos), que son las que principalmente se necesitan para los relevamientos y estudios que queremos poder lograr
- sería una solución más sencilla que un gimbal

También tiene algunas desventajas:
- la cámara/teléfono está más expuesta a golpes en aterrizajes/caídas
- en el caso de un teléfono, es más difícil de poner a grabar/sacar fotos (ya que la pantalla queda cubierta)

Para empezar a pensar en cómo adaptar la estructura, imprimimos la silueta del frame en hojas A3 y estuvimos haciendo brainstorming en los talleres del 28 y 29 de junio.

![imagen](https://user-images.githubusercontent.com/8480839/42137749-79b4d60a-7d48-11e8-844a-92a6017f5487.png)

Con eso hicimos algunos prototipos en papel/cartón (Bruno, Nacho, Facundo, Lucas y Braian se llevaron para seguir probando en sus casas). Mariano y Martín propusieron hacer prototipos impresos en 3D. Con Alejandrina, Tucho, Gustavo L. y Luciano estuvimos haciendo brainstorming y también probando con un prototipo hecho con cañitos metálicos (también con el objetivo de mejorar la resistencia de las patas, que son la parte que más frecuentemente se rompe). 

![imagen](https://user-images.githubusercontent.com/8480839/42137781-eaaac9fa-7d48-11e8-9493-8c2e6b434a35.png)

![imagen](https://user-images.githubusercontent.com/8480839/42137889-8a830e14-7d4a-11e8-887f-e9e0b68b06ea.png)

![imagen](https://user-images.githubusercontent.com/8480839/42137873-51c6447e-7d4a-11e8-868a-1a95b57b80da.png)

Seguimos explorando ideas...

**Comment by gpereyrairujo** [comment]
Este es la última versión de la estructura rediseñada:
[rediseño estructura - 05.zip](https://github.com/vuelaendron/vuela/files/2333562/rediseno.estructura.-.05.zip)
