### ISSUE TITLE
How to increase Bluetooth range - Cómo aumentar el alcance del Bluetooth

### ISSUE THREAD

**Issue by gpereyrairujo** [vuelaendron/vuela#7]
The Flone drone is controlled via Bluetooth, so its range is limited (10m in theory). We need ideas on how to increase this range - adding an external antenna to the Bluetooth module maybe...?
_El dron Flone se controla por Bluetooth, por lo que su alcance es limitado (10m en teoría). Necesitamos ideas de cómo incrementar este alcance - agregando una antena externa al módulo Bluetooth quizás...?_

**Comment by lotelx** [comment]
Hi,
I flyed a flone with BT more than 30 meters away working well, But I understand is scary.
Some years ago I made a hack with a extension of the BT antenna with a cable, and worked well.
http://wiki.flone.cc/index.php?title=P%C3%A1gina_principal#Extender_rango_de_Bluetooth

But instead of this I will recomend change the code to use Wifi and use a transparent Wifi to Serial module:
https://www.banggood.com/Geekcreit-DT-06-Wireless-WiFi-Serial-Port-Transparent-Transmission-Module-TTL-To-WiFi-p-1141047.html?p=JB1919987667201412AN

Don't forget to setup well the failsafe!

**Comment by gpereyrairujo** [comment]
Lo de la antena para el bluetooth lo queremos probar! Me gustaría medir bien el alcance antes y después... se me ocurre que con la misma app del flone, no? (viendo cuándo deja de moverse el indicador de "delay")

Y respecto del wifi, la app ahora no lo soporta, no? por eso dices "change the code"?
- - -
We will try the antenna for bluetooth! I would like to measure the range before and after... I think we can do it with the Flone app, right? (Checking when the "delay" indicator stops moving)

And regarding wifi, the app now does not support it, right? that's why you say "change the code"?

**Comment by gpereyrairujo** [comment]
Hice una prueba, dejando la Naze con el Bluetooth (sólo eso, no el flone armado) quieto en un punto, y buscando con la app el punto en el que en indicador de "delay" se deja de mover. Me alejaba hasta que se cortaba, y en ese momento retrocedía e iba girando hasta volver a tener señal. Es interesante ver cómo hay "puntos ciegos" donde el alcance es poco más de 10 metros, y otros donde llega hasta 70 metros! Seguramente tiene algo que ver con la posición y orientación de la antena del Bluetooth (no estaba horizontal).

![2018-05-11 mapa alcance bluetooth](https://user-images.githubusercontent.com/8480839/39932667-297a133e-5517-11e8-8b68-f36331a9d189.jpg)

- - -
I did a test, leaving the Naze with the Bluetooth module (only that, not the whole flone) in a fixed position, and searching with the app the point where the "delay" indicator stops moving. I walked away until I lost signal, and at that moment I would go backwards and sideways until I had signal again. It is interesting to see how there are "blind spots" where the range is just over 10 meters, and others where it reaches up to 70 meters! Surely it has something to do with the position and orientation of the Bluetooth antenna (it was not horizontal).

**Comment by gpereyrairujo** [comment]
Hicimos otra prueba similar. Esta vez, tomando el recaudo de colocar el módulo bluetooth de forma horizontal al igual que en el Flone. Esta vez la prueba fue con un modelo distinto de teléfono (Motorola en lugar de Huawei), y probablemente eso hizo que las mediciones de alcance fueran bastante mayores (entre 60 y 150 metros).
- - -
_We did another similar test. This time, placing the bluetooth module horizontally as in the Flone. This time the test was with a different phone model (Motorola instead of Huawei), and probably that caused the range measurements to be much higher (between 60 and 150 meters)._
- - -
![foto_bt_1](https://user-images.githubusercontent.com/8480839/40923985-8f96a0fa-67ec-11e8-9434-33a295055658.jpeg)

![bluetooth 2018-06-01](https://user-images.githubusercontent.com/8480839/40924001-9da63e58-67ec-11e8-8dff-f34a04a12986.jpg)

**Comment by lucianovelazquez** [comment]
Hola, hicimos algunas pruebas modificando la antena bluetooth. Compartimos el procedimiento y los resultados comparados con la antena sin modificar:
-Cortamos el circuito de la antena de la placa bluetooth, interrumpiendo el mismo en la entrada a la placa.
![image](https://user-images.githubusercontent.com/40550250/41825187-b2ffdbf4-77f2-11e8-9a8f-a87287e41ff5.png)
-Luego soldamos una antena nueva (cable de cobre de 32 mm delongitud tomado del centro de cable coaxil) evitando que la soldadura no una el circuito original de la antena para que esta no actúe.
![image](https://user-images.githubusercontent.com/40550250/41825268-d23f0930-77f3-11e8-8e28-93ccbb6bdaa7.png)
-Hicimos una prueba de alcance del bluetooth con la misma metodología que el post anterior (antena sin  modificar). Rojo: antena original. Azul: antena modificada (externa).
![image](https://user-images.githubusercontent.com/40550250/41825318-9c65924c-77f4-11e8-9f6c-c441cafba096.png)
Si bien el alcance fue muy variable, se logró un alcance máximo de 235 m y un mínimo de 93 m. 
-Luego de hacer esta prueba, volvimos a soldar el circuito de la antena original, dejando además la antena modificada ( externa). 
![image](https://user-images.githubusercontent.com/40550250/41825632-d2d1309e-77f8-11e8-9744-72adbc0f4109.png)
![image](https://user-images.githubusercontent.com/40550250/41825654-0923cefe-77f9-11e8-88c2-5993182caa04.png)

Próximamente vamos a probar las dos antenas (original + externa) funcionando en simultáneo.
